
all:
	make -C ./testcase1
	make -C ./testcase2
	make -C ./testcase3
	make -C ./testcase4
	make -C ./testcase5
	make -C ./testcase6
	make -C ./testcase7

clean:
	make clean -C ./testcase1
	make clean -C ./testcase2
	make clean -C ./testcase3
	make clean -C ./testcase4
	make clean -C ./testcase5
	make clean -C ./testcase6
	make clean -C ./testcase7
