
all:
	clang -g -S -emit-llvm -o testcase5-1.bc testcase5-1.c
	clang -g -S -emit-llvm -o testcase5-2.bc testcase5-2.c
	clang -g -S -emit-llvm -o testcase5-3.bc testcase5-3.c
	clang -g -S -emit-llvm -o testcase5-4.bc testcase5-4.c
	clang -g -S -emit-llvm -o testcase5-5.bc testcase5-5.c
	clang -g -S -emit-llvm -o testcase5-6.bc testcase5-6.c
	clang -g -S -emit-llvm -o testcase5-7.bc testcase5-7.c
	clang -g -S -emit-llvm -o testcase5-8.bc testcase5-8.c
	clang -g -S -emit-llvm -o testcase5-9.bc testcase5-9.c
	clang -g -S -emit-llvm -o testcase5-10.bc testcase5-10.c

clean:
	rm -f *.bc
