
all:
	clang -S -emit-llvm -o testcase7-1.bc testcase7-1.c
	clang -S -emit-llvm -o testcase7-2.bc testcase7-2.c
	clang -S -emit-llvm -o testcase7-3.bc testcase7-3.c
	clang -S -emit-llvm -o testcase7-4.bc testcase7-4.c
	clang -S -emit-llvm -o testcase7-5.bc testcase7-5.c
	clang -S -emit-llvm -o testcase7-6.bc testcase7-6.c
	clang -S -emit-llvm -o testcase7-7.bc testcase7-7.c
	clang -S -emit-llvm -o testcase7-11.bc testcase7-11.c

clean:
	rm -f *.bc
