
all:
	clang -S -emit-llvm -o testcase4-1.bc testcase4-1.c
	clang -S -emit-llvm -o testcase4-2.bc testcase4-2.c
	clang -S -emit-llvm -o testcase4-3.bc testcase4-3.c
	clang -S -emit-llvm -o testcase4-4.bc testcase4-4.c
	clang -S -emit-llvm -o testcase4-5.bc testcase4-5.c
	clang -S -emit-llvm -o testcase4-6.bc testcase4-6.c
	clang -S -emit-llvm -o testcase4-7.bc testcase4-7.c

clean:
	rm -f *.bc
